### ISSUE TITLE
Error: common_1.ReflectMetadata is not a function

### ISSUE THREAD

**Issue by hasanparasteh** [zMotivat0r/nest-api-version#6]
I'm using `"@nestjs/core": "^7.5.1"` and I ran nest-api-version as what documentation told and I got the below error:

```
TypeError: common_1.ReflectMetadata is not a function
    at Object.exports.ApiVersion (node_modules\@nestjsx\src\api-version.decorator.ts:4:3)
    at Object.<anonymous> (src\sysinfo\sysinfo.controller.ts:20:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (src\sysinfo\sysinfo.module.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**Comment by hasanparasteh** [comment]
I think the project is deprecated with this nestjs version...

**Comment by kosiakMD** [comment]
I have the same issue and seems @hasanparasteh are right
